services:
  mysql:
    restart: always
    image: mysql:8.0-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
